// Copyright 2020 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	tensorflowv1 "github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1"
	versioned "github.com/kubeflow/tf-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubeflow/tf-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/kubeflow/tf-operator/pkg/client/listers/tensorflow/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AmlTFJobInformer provides access to a shared informer and lister for
// AmlTFJobs.
type AmlTFJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AmlTFJobLister
}

type amlTFJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAmlTFJobInformer constructs a new informer for AmlTFJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAmlTFJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAmlTFJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAmlTFJobInformer constructs a new informer for AmlTFJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAmlTFJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzuremlV1().AmlTFJobs(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzuremlV1().AmlTFJobs(namespace).Watch(options)
			},
		},
		&tensorflowv1.AmlTFJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *amlTFJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAmlTFJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *amlTFJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tensorflowv1.AmlTFJob{}, f.defaultInformer)
}

func (f *amlTFJobInformer) Lister() v1.AmlTFJobLister {
	return v1.NewAmlTFJobLister(f.Informer().GetIndexer())
}
