// Copyright 2020 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	tensorflowv1 "github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAmlTFJobs implements AmlTFJobInterface
type FakeAmlTFJobs struct {
	Fake *FakeAzuremlV1
	ns   string
}

var amltfjobsResource = schema.GroupVersionResource{Group: "azureml.microsoft.com", Version: "v1", Resource: "amltfjobs"}

var amltfjobsKind = schema.GroupVersionKind{Group: "azureml.microsoft.com", Version: "v1", Kind: "AmlTFJob"}

// Get takes name of the amlTFJob, and returns the corresponding amlTFJob object, and an error if there is any.
func (c *FakeAmlTFJobs) Get(name string, options v1.GetOptions) (result *tensorflowv1.AmlTFJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(amltfjobsResource, c.ns, name), &tensorflowv1.AmlTFJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tensorflowv1.AmlTFJob), err
}

// List takes label and field selectors, and returns the list of AmlTFJobs that match those selectors.
func (c *FakeAmlTFJobs) List(opts v1.ListOptions) (result *tensorflowv1.AmlTFJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(amltfjobsResource, amltfjobsKind, c.ns, opts), &tensorflowv1.AmlTFJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &tensorflowv1.AmlTFJobList{ListMeta: obj.(*tensorflowv1.AmlTFJobList).ListMeta}
	for _, item := range obj.(*tensorflowv1.AmlTFJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested amlTFJobs.
func (c *FakeAmlTFJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(amltfjobsResource, c.ns, opts))

}

// Create takes the representation of a amlTFJob and creates it.  Returns the server's representation of the amlTFJob, and an error, if there is any.
func (c *FakeAmlTFJobs) Create(amlTFJob *tensorflowv1.AmlTFJob) (result *tensorflowv1.AmlTFJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(amltfjobsResource, c.ns, amlTFJob), &tensorflowv1.AmlTFJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tensorflowv1.AmlTFJob), err
}

// Update takes the representation of a amlTFJob and updates it. Returns the server's representation of the amlTFJob, and an error, if there is any.
func (c *FakeAmlTFJobs) Update(amlTFJob *tensorflowv1.AmlTFJob) (result *tensorflowv1.AmlTFJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(amltfjobsResource, c.ns, amlTFJob), &tensorflowv1.AmlTFJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tensorflowv1.AmlTFJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAmlTFJobs) UpdateStatus(amlTFJob *tensorflowv1.AmlTFJob) (*tensorflowv1.AmlTFJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(amltfjobsResource, "status", c.ns, amlTFJob), &tensorflowv1.AmlTFJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tensorflowv1.AmlTFJob), err
}

// Delete takes name of the amlTFJob and deletes it. Returns an error if one occurs.
func (c *FakeAmlTFJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(amltfjobsResource, c.ns, name), &tensorflowv1.AmlTFJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAmlTFJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(amltfjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &tensorflowv1.AmlTFJobList{})
	return err
}

// Patch applies the patch and returns the patched amlTFJob.
func (c *FakeAmlTFJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *tensorflowv1.AmlTFJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(amltfjobsResource, c.ns, name, pt, data, subresources...), &tensorflowv1.AmlTFJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*tensorflowv1.AmlTFJob), err
}
