// Copyright 2020 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1"
	scheme "github.com/kubeflow/tf-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AmlTFJobsGetter has a method to return a AmlTFJobInterface.
// A group's client should implement this interface.
type AmlTFJobsGetter interface {
	AmlTFJobs(namespace string) AmlTFJobInterface
}

// AmlTFJobInterface has methods to work with AmlTFJob resources.
type AmlTFJobInterface interface {
	Create(*v1.AmlTFJob) (*v1.AmlTFJob, error)
	Update(*v1.AmlTFJob) (*v1.AmlTFJob, error)
	UpdateStatus(*v1.AmlTFJob) (*v1.AmlTFJob, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AmlTFJob, error)
	List(opts metav1.ListOptions) (*v1.AmlTFJobList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AmlTFJob, err error)
	AmlTFJobExpansion
}

// amlTFJobs implements AmlTFJobInterface
type amlTFJobs struct {
	client rest.Interface
	ns     string
}

// newAmlTFJobs returns a AmlTFJobs
func newAmlTFJobs(c *AzuremlV1Client, namespace string) *amlTFJobs {
	return &amlTFJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the amlTFJob, and returns the corresponding amlTFJob object, and an error if there is any.
func (c *amlTFJobs) Get(name string, options metav1.GetOptions) (result *v1.AmlTFJob, err error) {
	result = &v1.AmlTFJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("amltfjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AmlTFJobs that match those selectors.
func (c *amlTFJobs) List(opts metav1.ListOptions) (result *v1.AmlTFJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AmlTFJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("amltfjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested amlTFJobs.
func (c *amlTFJobs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("amltfjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a amlTFJob and creates it.  Returns the server's representation of the amlTFJob, and an error, if there is any.
func (c *amlTFJobs) Create(amlTFJob *v1.AmlTFJob) (result *v1.AmlTFJob, err error) {
	result = &v1.AmlTFJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("amltfjobs").
		Body(amlTFJob).
		Do().
		Into(result)
	return
}

// Update takes the representation of a amlTFJob and updates it. Returns the server's representation of the amlTFJob, and an error, if there is any.
func (c *amlTFJobs) Update(amlTFJob *v1.AmlTFJob) (result *v1.AmlTFJob, err error) {
	result = &v1.AmlTFJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("amltfjobs").
		Name(amlTFJob.Name).
		Body(amlTFJob).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *amlTFJobs) UpdateStatus(amlTFJob *v1.AmlTFJob) (result *v1.AmlTFJob, err error) {
	result = &v1.AmlTFJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("amltfjobs").
		Name(amlTFJob.Name).
		SubResource("status").
		Body(amlTFJob).
		Do().
		Into(result)
	return
}

// Delete takes name of the amlTFJob and deletes it. Returns an error if one occurs.
func (c *amlTFJobs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("amltfjobs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *amlTFJobs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("amltfjobs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched amlTFJob.
func (c *amlTFJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AmlTFJob, err error) {
	result = &v1.AmlTFJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("amltfjobs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
