// Copyright 2020 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AmlTFJobLister helps list AmlTFJobs.
type AmlTFJobLister interface {
	// List lists all AmlTFJobs in the indexer.
	List(selector labels.Selector) (ret []*v1.AmlTFJob, err error)
	// AmlTFJobs returns an object that can list and get AmlTFJobs.
	AmlTFJobs(namespace string) AmlTFJobNamespaceLister
	AmlTFJobListerExpansion
}

// amlTFJobLister implements the AmlTFJobLister interface.
type amlTFJobLister struct {
	indexer cache.Indexer
}

// NewAmlTFJobLister returns a new AmlTFJobLister.
func NewAmlTFJobLister(indexer cache.Indexer) AmlTFJobLister {
	return &amlTFJobLister{indexer: indexer}
}

// List lists all AmlTFJobs in the indexer.
func (s *amlTFJobLister) List(selector labels.Selector) (ret []*v1.AmlTFJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AmlTFJob))
	})
	return ret, err
}

// AmlTFJobs returns an object that can list and get AmlTFJobs.
func (s *amlTFJobLister) AmlTFJobs(namespace string) AmlTFJobNamespaceLister {
	return amlTFJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AmlTFJobNamespaceLister helps list and get AmlTFJobs.
type AmlTFJobNamespaceLister interface {
	// List lists all AmlTFJobs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.AmlTFJob, err error)
	// Get retrieves the AmlTFJob from the indexer for a given namespace and name.
	Get(name string) (*v1.AmlTFJob, error)
	AmlTFJobNamespaceListerExpansion
}

// amlTFJobNamespaceLister implements the AmlTFJobNamespaceLister
// interface.
type amlTFJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AmlTFJobs in the indexer for a given namespace.
func (s amlTFJobNamespaceLister) List(selector labels.Selector) (ret []*v1.AmlTFJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AmlTFJob))
	})
	return ret, err
}

// Get retrieves the AmlTFJob from the indexer for a given namespace and name.
func (s amlTFJobNamespaceLister) Get(name string) (*v1.AmlTFJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("amltfjob"), name)
	}
	return obj.(*v1.AmlTFJob), nil
}
